// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9oqWuQS_OnxAcbN6Mfi7v_8ZpJqGezw',
    appId: '1:1033854183244:web:9c8619ec4d0304492451e9',
    messagingSenderId: '1033854183244',
    projectId: 'recipe-wallet-dc93e',
    authDomain: 'recipe-wallet-dc93e.firebaseapp.com',
    storageBucket: 'recipe-wallet-dc93e.firebasestorage.app',
    measurementId: 'G-XBTJ25NVEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiX6-bFz5C8EBdxsIEBcT0GuYtw7kk-Ek',
    appId: '1:1033854183244:android:f964252ab3fb415b2451e9',
    messagingSenderId: '1033854183244',
    projectId: 'recipe-wallet-dc93e',
    storageBucket: 'recipe-wallet-dc93e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rKU0hKkB4K2we7L_0SSnumzB6xRxAm4',
    appId: '1:1033854183244:ios:db57026cc6b894592451e9',
    messagingSenderId: '1033854183244',
    projectId: 'recipe-wallet-dc93e',
    storageBucket: 'recipe-wallet-dc93e.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rKU0hKkB4K2we7L_0SSnumzB6xRxAm4',
    appId: '1:1033854183244:ios:db57026cc6b894592451e9',
    messagingSenderId: '1033854183244',
    projectId: 'recipe-wallet-dc93e',
    storageBucket: 'recipe-wallet-dc93e.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );
}
